# Docker PostgreSQL Setup for Local Development

services:
  postgres:
    image: postgres:15
    container_name: portfolio-dev-db
    restart: always
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: portfolio_dev
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U portfolio_user -d portfolio_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
